In [10]:
import sys
sys.path.append('../scripts')  # Add the parent directory of 'scripts' to the Python path
from data_cleaner import DataPreprocessor
import pandas as pd

In [15]:
file_path= '../Data/rating.csv'
df=pd.read_csv(file_path)
df

       article_id  ... title_sentiment
0           81664  ...         Neutral
1           81667  ...        Positive
2           81694  ...        Negative
3           81695  ...         Neutral
4           81703  ...         Neutral
...           ...  ...             ...
58351      781108  ...         Neutral
58352      781129  ...         Neutral
58353      781235  ...        Negative
58354      781240  ...         Neutral
58355      781308  ...         Neutral

[58356 rows x 13 columns]

In [16]:
# null values in column

null_values_per_column = df.isnull().sum()
total_rows = df.shape[0]

# Calculate percentage of null values for each column
null_percentage_per_column = (null_values_per_column / total_rows) * 100

# Combine null values count and percentage into a DataFrame
null_summary = pd.DataFrame({'Null Values': null_values_per_column, 'Null Percentage': null_percentage_per_column})

print("Null values in each column:")
print(null_summary)

Null values in each column:
                 Null Values  Null Percentage
article_id                 0         0.000000
source_id              40585        69.547262
source_name                0         0.000000
author                  2163         3.706560
title                      0         0.000000
description               10         0.017136
url                        0         0.000000
url_to_image            3451         5.913702
published_at               0         0.000000
content                    0         0.000000
category                  21         0.035986
article                    0         0.000000
title_sentiment            0         0.000000

In [24]:
# Set the threshold for dropping columns
drop_threshold = 5
# Get the columns to drop and fill forward
columns_to_drop = null_summary[null_summary['Null Percentage'] > drop_threshold].index
columns_to_fill_forward = null_summary[null_summary['Null Percentage'] <= drop_threshold].index

# Drop columns with more than 3% missing values
df_dropped = df.drop(columns=columns_to_drop)

# Fill forward in columns with less than or equal to 3% missing values
df_filled = df_dropped.fillna(method='ffill')

# Print the columns dropped
print("Columns Dropped:")
print(columns_to_drop)

# Print the columns filled forward
print("Columns Filled Forward:")
print(columns_to_fill_forward)

# Print the resulting DataFrame
print("Resulting DataFrame after dropping and forward filling:")
print(df_filled)

Columns Dropped:
Index(['source_id', 'url_to_image'], dtype='object')
Columns Filled Forward:
Index(['article_id', 'source_name', 'author', 'title', 'description', 'url',
       'published_at', 'content', 'category', 'article', 'title_sentiment'],
      dtype='object')
Resulting DataFrame after dropping and forward filling:
       article_id  ... title_sentiment
0           81664  ...         Neutral
1           81667  ...        Positive
2           81694  ...        Negative
3           81695  ...         Neutral
4           81703  ...         Neutral
...           ...  ...             ...
58351      781108  ...         Neutral
58352      781129  ...         Neutral
58353      781235  ...        Negative
58354      781240  ...         Neutral
58355      781308  ...         Neutral

[58356 rows x 11 columns]

C:\Users\gecha\AppData\Local\Temp\ipykernel_1792\2270687693.py:11: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_filled = df_dropped.fillna(method='ffill')

In [25]:
df_filled

       article_id  ... title_sentiment
0           81664  ...         Neutral
1           81667  ...        Positive
2           81694  ...        Negative
3           81695  ...         Neutral
4           81703  ...         Neutral
...           ...  ...             ...
58351      781108  ...         Neutral
58352      781129  ...         Neutral
58353      781235  ...        Negative
58354      781240  ...         Neutral
58355      781308  ...         Neutral

[58356 rows x 11 columns]

In [27]:
# null values in column

null_values_per_column = df_filled.isnull().sum()
total_rows = df.shape[0]

# Calculate percentage of null values for each column
null_percentage_per_column = (null_values_per_column / total_rows) * 100

# Combine null values count and percentage into a DataFrame
null_summary = pd.DataFrame({'Null Values': null_values_per_column, 'Null Percentage': null_percentage_per_column})

print("Null values in each column:")
print(null_summary)

Null values in each column:
                 Null Values  Null Percentage
article_id                 0              0.0
source_name                0              0.0
author                     0              0.0
title                      0              0.0
description                0              0.0
url                        0              0.0
published_at               0              0.0
content                    0              0.0
category                   0              0.0
article                    0              0.0
title_sentiment            0              0.0

In [28]:
import os

# Create a directory if it doesn't exist
data_folder = 'Data'
if not os.path.exists(data_folder):
    os.makedirs(data_folder)

# Assuming you already have df_filled DataFrame

# Define the file path
file_path = os.path.join(data_folder, 'cleaned_data.csv')

# Save the cleaned DataFrame to a CSV file
df_filled.to_csv(file_path, index=False)

print(f"Cleaned data saved to {file_path}")

Cleaned data saved to Data\cleaned_data.csv